apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.db_name }}-backup-cm
  namespace: {{ .Values.namespace }}
data:
  MYSQL_DATABASE: "{{ .Values.ENV.mysql_database }}"
  MYSQL_USER: "{{ .Values.ENV.mysql_user }}"
  MYSQL_PASSWORD: "{{ .Values.ENV.mysql_password }}"
  MYSQL_HOST: "{{ .Values.db_name }}-svc"
