apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app_name }}-cm
  namespace: {{ .Values.namespace }}
data:
  NODE_ENV: "production"
  TRUST_PROXY: "true"
  PORT: "9001"
  TITLE: "{{ .Values.ENV.title }}"
  SKIN_NAME: "{{ .Values.ENV.skin_name }}"
  DEFAULT_PAD_TEXT: "{{ .Values.ENV.default_pad_text }}"
  ADMIN_PASSWORD: "{{ .Values.ENV.admin_password }}"
  SHOW_SETTINGS_IN_ADMIN_PAGE: "{{ .Values.ENV.show_settings_in_admin_page }}"
  SOFFICE: "{{ .Values.ENV.soffice }}"
  REQUIRE_SESSION: "{{ .Values.ENV.require_session }}"
  EDIT_ONLY: "{{ .Values.ENV.edit_only }}"
  AUTOMATIC_RECONNECTION_TIMEOUT: "{{ .Values.ENV.automatic_reconnection_timeout }}"
  IMPORT_MAX_FILE_SIZE: "{{ .Values.ENV.import_max_file_size }}"
  DISABLE_IP_LOGGING: "{{ .Values.ENV.disable_ip_logging }}"
  PAD_OPTIONS_LANG: "{{ .Values.ENV.pad_options_lang }}"
  PAD_OPTIONS_NO_COLORS: "{{ .Values.ENV.pad_options_no_colors }}"
  PAD_OPTIONS_SHOW_CONTROLS: "{{ .Values.ENV.pad_options_show_controls }}"
  PAD_OPTIONS_SHOW_CHAT: "{{ .Values.ENV.pad_options_show_chat }}"
  PAD_OPTIONS_SHOW_LINE_NUMBERS: "{{ .Values.ENV.pad_options_show_line_numbers }}"
  PAD_OPTIONS_USE_MONOSPACE_FONT: "{{ .Values.ENV.pad_options_use_monospace_font }}"
  {{- if .Values.ENV.pad_options_user_name }}
  PAD_OPTIONS_USER_NAME: "{{ .Values.ENV.pad_options_user_name }}"
  {{- end }}
  {{- if .Values.ENV.pad_options_user_color }}
  PAD_OPTIONS_USER_COLOR: "{{ .Values.ENV.pad_options_user_color }}"
  {{- end }}
  PAD_OPTIONS_RTL: "{{ .Values.ENV.pad_options_rtl }}"
  PAD_OPTIONS_ALWAYS_SHOW_CHAT: "{{ .Values.ENV.pad_options_always_show_chat }}"
  PAD_OPTIONS_CHAT_AND_USERS: "{{ .Values.ENV.pad_options_chat_and_users }}"
  DB_CHARSET: "utf8mb4"
  DB_TYPE: "mysql"
  DB_HOST: "{{ .Values.db_name }}-svc"
  DB_PORT: "3306"
  DB_NAME: "{{ .Values.ENV.mysql_database }}"
  DB_USER: "{{ .Values.ENV.mysql_user }}"
  DB_PASS: "{{ .Values.ENV.mysql_password }}"
  BUGSNAG_API_KEY: "{{ .Values.ENV.bugsnag_api_key }}"
  BUGSNAG_APP_VERSION: "{{ .Values.app_image_tag }}"
  BUGSNAG_ENV: "{{ .Values.ENV.app_env }}"
