apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app_name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.app_replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app_name }}
    spec:
      securityContext:
        runAsUser: 5001
        fsGroup: 5001
      # Fixes DNS resolution fails for external domains from Alpine-based containers
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      initContainers:
      # Copy the image's plugins into the k8s volume if empty
      - name: copy-plugins
        image: "unillett/etherpad:{{ .Values.app_image_tag }}"
        command:
          - sh
          - -c
          - |
            if [ -z "$(ls -A /mnt/plugins-data 2>/dev/null)" ]; then
              echo "plugins-data is empty, copying plugins from image..."
              cp -a {{ .Values.app_workdir }}/src/plugin_packages/. /mnt/plugins-data/
            else
              echo "plugins-data already populated, skipping copy."
            fi
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: {{ .Values.app_volume_name }}
          mountPath: /mnt/plugins-data
          subPath: plugins-data
      # Enforce permissions of mounted directories to ensure the app can write to them
      - name: enfoce-permissions
        image: busybox:latest
        command:
          - sh
          - -c
          - chown -R 5001:0 {{ .Values.app_workdir }}/src/plugin_packages {{ .Values.app_workdir }}/var
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: {{ .Values.app_volume_name }}
          mountPath: {{ .Values.app_workdir }}/src/plugin_packages
          subPath: plugins-data
        - name: {{ .Values.app_volume_name }}
          mountPath: {{ .Values.app_workdir }}/var
          subPath: var-data
      - name: wait-for
        image: ghcr.io/patrickdappollonio/wait-for:latest
        command:
          - /wait-for
        args:
          - --host="{{ .Values.db_name }}-svc:3306"
          - --verbose
      containers:
      - name: {{ .Values.app_name }}
        image: "unillett/etherpad:{{ .Values.app_image_tag }}"
        envFrom:
          - configMapRef:
              name: {{ .Values.app_name }}-cm
        ports:
        - containerPort: 9001
          name: {{ .Values.app_name }}
          protocol: TCP
        volumeMounts:
        - name: {{ .Values.app_volume_name }}
          mountPath: {{ .Values.app_workdir }}/src/plugin_packages
          subPath: plugins-data
        - name: {{ .Values.app_volume_name }}
          mountPath: {{ .Values.app_workdir }}/var
          subPath: var-data
        - name: {{ .Values.app_volume_name }}
          mountPath: {{ .Values.app_workdir }}/node_modules
          subPath: node-data
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "{{ .Values.app_workdir }}/k8s-poststart.sh"]
        resources:
          requests:
            memory: "{{ .Values.app_memory_request }}"
            cpu: "{{ .Values.app_cpu_request }}"
          limits:
            memory: "{{ .Values.app_memory_limit }}"
            cpu: "{{ .Values.app_cpu_limit }}"
      volumes:
      - name: {{ .Values.app_volume_name }}
        persistentVolumeClaim:
          claimName: {{ .Values.app_name }}-pvc
