apiVersion: v2
name: helm-logging
description: Helm chart for VictoriaLogs
version: 1.0.0
dependencies:
  - name: victoria-logs-single
    version: 0.13.9
    repository: https://victoriametrics.github.io/helm-charts
  - name: victoria-logs-collector
    version: 0.3.7
    repository: https://victoriametrics.github.io/helm-charts
