victoria-logs-single:
  server:
    retentionPeriod: 15d
    persistentVolume:
      size: 50Gi
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      hosts:
        - name: my.victorialogs-host.com
          path:
            - "/"
          port: http
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 512Mi
victoria-logs-collector:
  remoteWrite:
    - url: http://vls-victoria-logs-single-server:9428
      maxDiskUsagePerURL: 10GB
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
