namespace: logging
ingress_host: my.victorialogs-host.com
victoria-logs-single:
  server:
    retentionPeriod: 15d
    persistentVolume:
      size: 50Gi
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 512Mi
vmui:
  auth:
    enabled: true
    username: admin
    password: admin
victoria-logs-collector:
  remoteWrite:
    - url: http://logging-victoria-logs-single-server:9428
      maxDiskUsagePerURL: 10GB
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
