{{- if .Values.vmui.auth.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.namespace }}-auth-secret
type: kubernetes.io/basic-auth
stringData:
  username: "{{ .Values.vmui.auth.username }}"
  password: "{{ .Values.vmui.auth.password }}"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth
  namespace: {{ .Values.namespace }}
spec:
  basicAuth:
    secret: {{ .Values.namespace }}-auth-secret
    removeHeader: true
{{- end }}
