{{- if .Values.vmui.auth.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.namespace }}-auth-secret
type: Opaque
stringData:
  users: |
    {{ .Values.vmui.auth.username }}:{PLAIN}{{ .Values.vmui.auth.password }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth
  namespace: {{ .Values.namespace }}
spec:
  basicAuth:
    secret: {{ .Values.namespace }}-auth-secret
    removeHeader: true
{{- end }}
