apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.namespace }}-server-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    {{- if .Values.vmui.auth.enabled }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Values.namespace }}-auth@kubernetescrd
    {{- end }}
spec:
  ingressClassName: traefik
  rules:
  - host: {{ .Values.ingress_host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: logging-victoria-logs-single-server
            port:
              number: 9428
