apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app_name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app_name }}
    spec:
      containers:
      - name: vaultwarden
        image: "vaultwarden/server:{{ .Values.image_tag }}"
        #command: ["sleep"]
        #args: ["3000"]
        envFrom:
          - configMapRef:
              name: {{ .Values.app_name }}-cm
        ports:
        - containerPort: 80
          name: {{ .Values.app_name }}-ui
          protocol: TCP
        volumeMounts:
        - name: {{ .Values.volume_name }}
          mountPath: /data
        resources:
          requests:
            memory: "{{ .Values.memory_request }}"
            cpu: "{{ .Values.cpu_request }}"
          limits:
            memory: "{{ .Values.memory_limit }}"
            cpu: "{{ .Values.cpu_limit }}"
      volumes:
      - name: {{ .Values.volume_name }}
        persistentVolumeClaim:
          claimName: {{ .Values.app_name }}-pvc
