apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ .Values.namespace }}-keda-trigger-auth-mysql
  namespace: {{ .Values.namespace }}
spec:
  env:
  - parameter: connectionString
    name: MYSQL_CONN_STR
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Values.worker_name }}-hpa
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    name: {{ .Values.worker_name }}
  minReplicaCount: {{ .Values.worker_min_replicas }}
  maxReplicaCount: {{ .Values.worker_max_replicas }}
  cooldownPeriod: {{ .Values.hpa_cooldown }}
  triggers:
  - type: mysql
    metadata:
      queryValue: "{{ .Values.hpa_query_value }}"
      activationQueryValue: "{{ .Values.hpa_activation_value }}"
      query: "SELECT COUNT(*) AS count FROM cache_locks WHERE `key` LIKE '%ProcessFile%'"
    authenticationRef:
      name: {{ .Values.namespace }}-keda-trigger-auth-mysql

