apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-mysql
  namespace: {{ .Values.namespace }}
spec:
  env:
    - parameter: host
      name: "10.42.3.3"
    - parameter: port
      name: "3306"
    - parameter: dbName
      name: "{{ .Values.ENV.mysql_database }}"
    - parameter: username
      name: "{{ .Values.ENV.mysql_user }}"
    - parameter: password
      name: "{{ .Values.ENV.mysql_password }}"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Values.worker_name }}-keda-hpa
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    name: {{ .Values.worker_name }}
  triggers:
  - type: mysql
    metadata:
      queryValue: "{{ .Values.hpa_query_value }}"
      activationQueryValue: "{{ .Values.hpa_activation_value }}"
      query: "SELECT COUNT(*) AS count FROM cache_locks WHERE `key` LIKE '%ProcessFile%'"
    authenticationRef:
      name: keda-trigger-auth-mysql
