apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app_name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app_name }}
    spec:
      containers:
      - name: mailpit
        image: axllent/mailpit:{{ .Values.image_tag }}
        #command: ["sleep"]
        #args: ["3000"]        
        envFrom:
          - configMapRef:
              name: {{ .Values.app_name }}-cm
        ports:
        - containerPort: 8025
          name: {{ .Values.app_name }}-ui
          protocol: TCP
        - containerPort: 1025
          name: {{ .Values.app_name }}-smtp
          protocol: TCP
        volumeMounts:
        - name: data-volume
          mountPath: /mpit
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: {{ .Values.app_name }}-pvc
