apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mailpit-ingress
  namespace: {{ .Values.namespace }}
spec:
 rules:
  - host: {{ .Values.ingress_host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Values.app_name }}-svc
            port:
              number: 8025
