apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app_name }}-svc
  name: {{ .Values.app_name }}-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: "{{ .Values.app_name }}"
    port: 80
    protocol: TCP
    targetPort: 3001
  selector:
    app: {{ .Values.app_name }}
  type: ClusterIP
status:
  loadBalancer: {}
