apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookstack-ingress-app
  namespace: {{ .Values.namespace }}
spec:
 rules:
  - host: {{ .Values.app_ingress_host_cluster }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Values.app_name }}-svc
            port:
              number: 80
  - host: {{ .Values.app_ingress_host_alias }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Values.app_name }}-svc
            port:
              number: 80
