apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.db_name }}-svc
  name: {{ .Values.db_name }}-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: "{{ .Values.db_name }}"
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: {{ .Values.db_name }}
  type: ClusterIP
status:
  loadBalancer: {}
