apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app_name }}-svc
  name: {{ .Values.app_name }}-svc
  namespace: {{ .Values.namespace }}
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: "http-cookie"
    traefik.ingress.kubernetes.io/service.sticky.cookie.secure: "true"
spec:
  ports:
  - name: "{{ .Values.app_name }}"
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Values.app_name }}
  type: ClusterIP
status:
  loadBalancer: {}
