apiVersion: v1
kind: Service
metadata:
  labels:
    app: deploy-jeanluc
  name: svc-deploy-jeanluc
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: deploy-jeanluc
  type: ClusterIP
