apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.db_name }}-backup
  namespace: {{ .Values.namespace }}
spec:
  timeZone: {{ .Values.ENV.timezone }}
  schedule: "0 1 * * *"  # Runs daily at 1 AM
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: db-backup
              image: "postgis/postgis:{{ .Values.db_image_tag }}"
              envFrom:
                - configMapRef:
                    name: {{ .Values.db_name }}-backup-cm
              command: ["/bin/sh", "-c"]
              args:
                - |
                  find /dumps -type f -mtime +30 -exec rm {} \; && \
                  PGPASSWORD=$$POSTGRES_PASSWORD pg_dump \
                    -h $$POSTGRES_HOST \
                    -U $$POSTGRES_USER \
                    -d $$POSTGRES_DB \
                    -F c \
                    -Z 9 \
                    -f /dumps/$(date +\%Y\%m\%d\%H\%M\%S).dump
              volumeMounts:
                - name: {{ .Values.db_volume_name }}
                  mountPath: /dumps
                  subPath: dumps
          restartPolicy: OnFailure
          volumes:
            - name: {{ .Values.db_volume_name }}
              persistentVolumeClaim:
                claimName: {{ .Values.db_volume_name }}-{{ .Values.db_name }}-0
