apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: transport
  namespace: {{ .Values.namespace }}
spec:
  forwardingTimeouts:
    # Keep idle TCP connections alive for 2 minutes
    idleConnTimeout: 120
