name: ci
on: [push, pull_request]

jobs:
  kubeconform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Validate
      uses: nlamirault/helm-kubeconform-action@v0.2.0
      with:
        charts: ./
