name: ci
on: [push, pull_request]

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kubernetes tools
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Install kubeconform
        run: |
          curl -sLO https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz
          tar -xzf kubeconform-linux-amd64.tar.gz
          sudo mv kubeconform /usr/local/bin/kubeconform
          kubeconform -v

      - name: Render and validate all Helm charts
        run: |
          # Find all Helm chart directories and process each one
          set -e
          ERROR=false
          find . -name 'Chart.yaml' -exec dirname {} \; | while read chart_dir; do
            echo "Processing Helm chart in $chart_dir"
            mkdir -p rendered_templates/$chart_dir
            if ! helm template $chart_dir --output-dir rendered_templates/$chart_dir; then
              echo "Helm template failed for $chart_dir"
              ERROR=true
            fi
            if ! find rendered_templates/$chart_dir -name '*.yaml' -exec kubeconform -strict {} +; then
              echo "kubeconform validation failed for $chart_dir"
              ERROR=true
            fi
          done
          if [ "$ERROR" = true ]; then
            exit 1
          fi

      - name: Lint all Helm charts
        run: |
          set -e
          ERROR=false
          find . -name 'Chart.yaml' -exec dirname {} \; | while read chart_dir; do
            echo "Linting Helm chart in $chart_dir"
            if ! helm lint $chart_dir; then
              echo "Helm lint failed for $chart_dir"
              ERROR=true
            fi
          done
          if [ "$ERROR" = true ]; then
            exit 1
          fi
